### ISSUE TITLE
Example does not respond?

### ISSUE THREAD

**Issue by kwhitley** [borderless/worker-sentry#2]
Unless I’m mistaken, your example returns nothing (and thus would throw in CF land). event.waitUntil(Promise) resolves *after* you've returned a Response, so you'd still need to return something (a Response) after that line to hand the actual Response to the request. 😁

**Comment by blakeembrey** [comment]
I understand how CF workers work, I’ve been using this in production without issue for a while now. The example is purely an example, of course you’d need to actually implement `handler` otherwise it’s going to fail. The assumption in my example was that the user would create `handler` and can return `Response` there. If you’d like to contribute an improved example, feel free to open a PR.

Edit: You can event have the catch handler return a 500 in your update to the example if you’d like.

**Comment by kwhitley** [comment]
Wasn't implying that you didn't (understand CF workers), just that the example would throw as shown.  Nothing to do with the missing handler really - in the event that an error was thrown, it would go into the catch block (no longer the handler), where it returns nothing to the user... the `event.waitUntil` would just silently record the error, but I'm pretty sure the user would see a nasty Cloudflare Error page thanks to the lack of `Response` return.

Anyway, happy to PR a little fix to the example - cheers~
